# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=100, verbose_name='Titol de la categoria')),
            ],
            options={
                'ordering': ['nom_categoria'],
            },
        ),
    ]
